config/routes.rb
Rails.application.routes.draw do

  scope path: '/waypoints', controller: :waypoints do
    get 'last_position' => :last_position
  end

  resources :waypoints do
    collection do
      get 'polyline'
    end
  end


  resources :stopovers

  root 'waypoints#index'
  get 'infos' => 'waypoints#infos'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/stopover.rb
class Stopover
  include ActiveModel::Model

  attr_accessor :latitude, :longitude, :from_date, :to_date
  validates :latitude, :longitude, :from_date, :to_date, presence: true

  def to_s
    "Stopover=[#{'%.4f' % self.latitude},#{'%.5f' % self.longitude} for #{ '%.2f' % ((self.to_date - self.from_date) / 1.day) }d]"
  end


end

app/models/waypoint.rb
class Waypoint < ApplicationRecord
  acts_as_mappable :lat_column_name => :latitude,
                   :lng_column_name => :longitude

  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :date, presence: true
  validates :date, uniqueness: true

  belongs_to :from, :class_name => "Waypoint", foreign_key: 'from_id', optional: true

  scope :by_date, -> { order('date ASC, id DESC') }


  def from
    Waypoint.where("date < ?", date).order(date: :asc).last
  end

  def to
    Waypoint.where("date > ?", date).order(date: :asc).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stopovers_controller.rb
class StopoversController < ApplicationController

  protect_from_forgery with: :null_session

  def index

    # let it be iframed
    response.headers.delete "X-Frame-Options"

    @stopovers = StopoverService.new.perform

    respond_to do |format|
      format.json { render :index, status: :ok}
    end
  end

end

app/controllers/waypoints_controller.rb
class WaypointsController < ApplicationController

  protect_from_forgery with: :null_session

  before_action :set_waypoint, only: [:show, :edit, :update, :destroy]

  # GET /waypoints
  # GET /waypoints.json
  def index

    # let it be iframed
    response.headers.delete "X-Frame-Options"

    obtain_waypoints

    respond_to do |format|
      format.html
      format.json { render :index, status: :ok}
    end
  end

  def last_position
    @waypoint = Waypoint.order("date").last
    render "waypoints/show.json"
  end

  def polyline
    # let it be iframed
    response.headers.delete "X-Frame-Options"

    bounds = params.dig(:bounds)

    redis_key = "cached_encoded_polyline:#{bounds}"
    encoded = REDIS.get(redis_key) unless bounds.nil?

    if encoded
      Rails.logger.info("cache: encoded polyline hit: " + encoded)
    else
      Rails.logger.info("cache: encoded polyline not found. Constructing...")

      obtain_waypoints
      latlngs = @waypoints.map {|w| [w.latitude, w.longitude]}
      encoded = Polylines::Encoder.encode_points(latlngs)

      REDIS.set(redis_key, encoded)
      Rails.logger.info("polyline input: #{encoded}")
    end

    render plain: encoded

  end

  def infos
    info = {
        total_nm: total_nm,
        last_update: last_update
    }
    render json: info
  end

  def last_update
    Waypoint.order(:date).last.date
  end

  def total_nm
    total = 0
    last_waypoint = nil

    Waypoint.order(:date).each do |w|

      if last_waypoint
        dist = last_waypoint.distance_to(w)
        date_diff = w.date - last_waypoint.date
        raise "order is not good" if date_diff < 0
        current_speed = dist / date_diff * 3600
        # puts "#{w.id} speed: #{current_speed}nm/h"
        if current_speed < 0 || current_speed > 15
          puts "ignoring waypoint=#{w.id}, last wp=#{last_waypoint.id}"
          suspicious = true
        else
          total = total + dist
        end
      end
      last_waypoint = w unless suspicious
    end
    total
  end

  # GET /waypoints/1
  # GET /waypoints/1.json
  def show
  end

  # GET /waypoints/new
  def new
    @waypoint = Waypoint.new
  end

  # GET /waypoints/1/edit
  def edit
  end

  # POST /waypoints
  # POST /waypoints.json
  def create
    @waypoint = Waypoint.new(waypoint_params)
    respond_to do |format|
      if @waypoint.save
        FromIndexService.new.perform
        REDIS.flushall
        format.html { redirect_to @waypoint, notice: 'Waypoint was successfully created.' }
        format.json { render :show, status: :created, location: @waypoint }
      else
        format.html { render :new }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waypoints/1
  # PATCH/PUT /waypoints/1.json
  def update
    respond_to do |format|
      if @waypoint.update(waypoint_params)
        REDIS.flushall
        format.html { redirect_to @waypoint, notice: 'Waypoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @waypoint }
      else
        format.html { render :edit }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waypoints/1
  # DELETE /waypoints/1.json
  def destroy
    @waypoint.destroy
    FromIndexService.new.perform
    REDIS.flushall
    respond_to do |format|
      format.html { redirect_to waypoints_url, notice: 'Waypoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def obtain_waypoints
    bounds = params.dig(:bounds)

    if bounds

      json_parse = JSON.parse(bounds)
      south = json_parse["south"]
      west = json_parse["west"]
      east = json_parse["east"]
      north = json_parse["north"]

      # puts "this are the params: #{south}  #{west}  #{north}  #{east}"
      sw = Geokit::LatLng.new(south, west)
      ne = Geokit::LatLng.new(north, east)

      waypoints = Waypoint.in_bounds([sw, ne]).order(date: :desc).to_a

      Rails.logger.info("Waypoints in bounds: #{waypoints}")

      # adding the edges
      @waypoints = waypoints.map {|wp| [wp.to, wp, wp.from]}.reduce([], &:concat).uniq.compact
    else
      @waypoints = Waypoint.order(date: :desc).limit(4)
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_waypoint
    @waypoint = Waypoint.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def waypoint_params
    params.require(:waypoint).permit(:latitude, :longitude, :logbook, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/waypoints_helper.rb
module WaypointsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coderouge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type="text/javascript" charset="utf-8">
      var __GOOGLE_MAP_API_KEY__ = "<%=Rails.application.credentials.google_maps_api_key%>";
      var __FLAG_PNG__ = "<%= image_url('red_flag1.png') %>";
      var __BOAT_SVG__ = "<%= image_url('boat.svg') %>";
    </script>
    <%= yield(:head_tags) %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/waypoints/_form.html.erb
<%= form_with(model: waypoint, local: true) do |form| %>
  <% if waypoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(waypoint.errors.count, "error") %> prohibited this waypoint from being saved:</h2>

      <ul>
      <% waypoint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :logbook %>
    <%= form.text_area :logbook %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/waypoints/edit.html.erb
<h1>Editing Waypoint</h1>

<%= render 'form', waypoint: @waypoint %>

<%= link_to 'Show', @waypoint %> |
<%= link_to 'Back', waypoints_path %>

app/views/waypoints/index.html.erb
<!-- bigbang -->
<div id="map-view">
  <map-view></map-view>
</div>

<!--<div>-->
  <!--Le portable de Quentin gît au fond de l'eau. Ne vous vexez pas s'il tarde à répondre.-->
  <!--Et vous pouvez toujours le joindre sur son mail: <b>prénom.nom@gmail.com</b>-->
<!--</div>-->

<%= javascript_pack_tag 'waypoints/map'%>

app/views/waypoints/new.html.erb
<h1>New Waypoint</h1>

<%= render 'form', waypoint: @waypoint %>

<%= link_to 'Back', waypoints_path %>

app/views/waypoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @waypoint.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @waypoint.longitude %>
</p>

<p>
  <strong>Logbook:</strong>
  <%= @waypoint.logbook %>
</p>

<p>
  <strong>Date:</strong>
  <%= @waypoint.date %>
</p>

<%= link_to 'Edit', edit_waypoint_path(@waypoint) %> |
<%= link_to 'Back', waypoints_path %>